### ISSUE TITLE
[Error] IAX trunk event queue full

### ISSUE THREAD

**Issue by raheelkhanyyz** [jaracil/iax#2]
Hi, 

i registered to a asterisk peer  after one minute or so , it gives this error 
"[Error] IAX trunk event queue full" and then unregister , could you plz point me out in the right direction . 

the following are the trunk options that i set :

		FrameTimeout:     5,
		EvtQueueSize:     200,
		SendQueueSize:    200,
		CallEvtQueueSize: 200,
		CallFrmQueueSize: 200,
		DebugMiniframes:  false,
		
		

thanks .

**Comment by jaracil** [comment]
Hi. You must poll the events using WaitEvent method.
See recently pushed example...
Bye.

**Comment by raheelkhanyyz** [comment]
bundle of thanks !!!
